Commenting out the restore warnings and added a line recommended by GHE support

diff --git a/share/github-backup-utils/ghe-restore-repositories b/share/github-backup-utils/ghe-restore-repositories
--- a/share/github-backup-utils/ghe-restore-repositories
+++ b/share/github-backup-utils/ghe-restore-repositories
@@ -66,6 +66,7 @@ cleanup() {
   for hostname in $hostnames; do
     ghe-gc-enable $ssh_config_file_opt $hostname:$port || true
   done
+  ghe-ssh "$GHE_HOSTNAME" -- cp $remote_tempdir/repo_warnings /home/admin/repo-warnings
   ghe-ssh "$GHE_HOSTNAME" -- rm -rf $remote_tempdir
   rm -rf $tempdir
 }
@@ -191,10 +192,10 @@ else
 fi
 bm_end "$(basename $0) - Updating repository info data"
 
-restore_warnings="$(ghe-ssh "$GHE_HOSTNAME" -- cat "$remote_warnings" 2>/dev/null || true)"
-if [ -n "$restore_warnings" ]; then
-  echo "Warning: One or more repository networks failed to restore successfully. Please contact GitHub Enterprise Support for assistance."
-  echo "$restore_warnings"
-fi
+# restore_warnings="$(ghe-ssh "$GHE_HOSTNAME" -- cat "$remote_warnings" 2>/dev/null || true)"
+# if [ -n "$restore_warnings" ]; then
+#   echo "Warning: One or more repository networks failed to restore successfully. Please contact GitHub Enterprise Support for assistance."
+#   echo "$restore_warnings"
+# fi
 
 bm_end "$(basename $0)"
